[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "slideshow"
version = "0.0.1"
readme = "README.md"
dependencies = [
  'click',
  'pillow',
  'pygame',
  'exifread',
]


[project.scripts]
slideshow = "slideshow:cli"
